__copyright__ = '(c) Webyog, Inc'
__author__ = 'Vishal P.R'
__license__ = 'GPL'
__email__ = 'support@sealion.com'

AGENT_ERR_SUCCESS = 0
AGENT_ERR_TERMINATE = 20
AGENT_ERR_FAILED_DAEMONIZE_1 = 21
AGENT_ERR_FAILED_DAEMONIZE_2 = 22
AGENT_ERR_ALREADY_RUNNING = 23
AGENT_ERR_FAILED_PID_FILE = 24
AGENT_ERR_FAILED_TERMINATE = 25
AGENT_ERR_FAILED_OPEN_LOG = 26
AGENT_ERR_FAILED_INITIALIZE = 27
AGENT_ERR_FAILED_CONNECT = 28
AGENT_ERR_FAILED_UNREGISTER = 29
AGENT_ERR_FAILED_FIND_USER = 30
AGENT_ERR_FAILED_CHANGE_GROUP_OR_USER = 31
